### ISSUE TITLE
Unable to add spacing to the star background image

### ISSUE THREAD

**Issue by annamisak** [annamisak/dsn1676-assignment-1#1]
I decided to add the star icon as a background image with the H1 tag. Overall it works well, except for unable to add additional spacing to the outside sides where the stripes touching the stars. 

How can I fix that? 

ask @thomasjbradley

**Comment by thomasjbradley** [comment]
You can change the `background-position` a little bit, this line right here:
https://github.com/annamisak/dsn1676-assignment-1/blob/gh-pages/css/main.css#L48

I would try something like this:

``` css
background-position: calc(100% - 10px) center, 10px center;
```

**Comment by annamisak** [comment]
Thank you!
